### ISSUE TITLE
Output all GISAID metadata fields for shiptv visualization

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#6]
Let users decide which metadata to highlight in a shiptv tree visualization.

**Comment by nhhaidee** [comment]
Params: skip_gisaid_epi_il, skip_date, skip_location, skip_length, skip_host, skip_age, skip_sex, skip_pangolin_lineage, skip_aa_sub  will be added. These params will be set as False by default.

**Comment by peterk87** [comment]
Why would those things be skipped? Are they processes in the workflow? I am a little confused. 

I meant that all metadata from the GISAID metadata table be output to the metadata table supplied to shiptv.

**Comment by nhhaidee** [comment]
I meant, by the default these columns will be kept in visualization as we did normally. User can now change to True (in nextflow_config) to remove columns in shiptv metadata, so that it will not display in visualization.

**Comment by peterk87** [comment]
Sorry, if I was clear. I meant that by default no fields/columns from the
GISAID metadata table should be dropped for visualization. Users can select
what fields they wish to show in the shiptv tree. It looks like the
"output-metadata1" is the mostly unaltered GISAID metadata table filtered
for samples of interest; is this the output table used with shiptv?

The argument names "output-metadata1/2" aren't very descriptive and the
help messages are very unclear about what their intended purpose is. If one
of the metadata tables is for Nextstrain, then rename it to
"--nextstrain-metadata".

Also this is an unsafe way of renaming fields if you don't have control
over the input format:

https://github.com/nhhaidee/scovtree/blob/b9ac5166b6be6531d86a2a310f371bb094c50060/bin/filter_gisaid_sequences.py#L119

What if GISAID changes the fields they output? New fields added? Fields
Dropped? Or if the order of the fields changes? Replacing the column names
that have been parsed by Pandas with a list assumes a certain order and a
certain number of fields. It's much safer to use the Pandas DataFrame
rename method with a dict of old to new column names.

On a related note, if you're filtering the metadata table for Nextstrain
and require specific fields to be present, it may be better to filter for
the columns of interest rather than to drop columns. It would also be a
good idea to validate that the expected fields are actually present in the
input metadata table.

**Comment by nhhaidee** [comment]
There are 22 columns in the gisaid metadata, based on the result you sent me before, workflow drops other columns and keep columns are gisaid_epi_il, date, location, length, host, age, sex, pangolin_lineage for visualization. I will change workflow so it keeps all columns by default and allow options to drop columns that user doesn't want

I am simplifying workflow and renaming keywords in descriptive way.

**Comment by nhhaidee** [comment]
Work in progress (https://github.com/nhhaidee/scovtree/pull/11)

**Comment by nhhaidee** [comment]
Options are added so that user can drop/keep particular columns for Shiptv metadata

--max_taxa (default: 75): maximum taxa of the phylogenetic tree in SHIPTV Visualization                            
--skip_virus_name (default: false)                       
--skip_type (default: false)                                
--skip_accession_id (default: false)                     
--skip_collection_date (default: false)                   
--skip_location (default: false)                           
--skip_additional_location_information (default: false)    
--skip_sequence_length (default: false)                    
--skip_host (default: false)                              
--skip_patient_age (default: false)                     
--skip_gender (default: false)                           
--skip_clade (default: false)                        
--skip_pango_lineage (default: false)               
--skip_pangolin_version (default: false)                 
--skip_variant (default: false)                        
--skip_aa_substitutions  (default: false)            
--skip_submission_date (default: false)              
--skip_is_reference (default: false)                    
--skip_is_complete (default: false)                  
--skip_is_high_coverage (default: false)              
--skip_is_low_coverage (default: false)             
--skip_n_content (default: false)                
--skip_gc_content (default: false)                     
--skip_aa_substitution_change (default: false)

**Comment by peterk87** [comment]
What about one CLI option for dropping columns (e.g. `--drop_gisaid_columns "Type,Virus Name"` where `drop_columns` takes a comma separated string of column names to drop) instead a separate option for each column that might appear in the GISAID metadata?

Also, using "skip" implies not a task rather than dropping a column.

**Comment by nhhaidee** [comment]
OK. I will take account this enhancement.

**Comment by nhhaidee** [comment]
Fixed by PR https://github.com/nhhaidee/scovtree/pull/30
